swagger: "2.0"
info:
  description: "API for Rate Reader"
  version: "0.0.1"
  title: "Rate Reader"
host: ""
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /api/v1/help:
    get:
      summary: Service API documentation
      description: |
        Swagger documentation rendered by ReDoc
      produces:
        - text/html
      responses:
        200:
          description: Documentation page
      tags:
        - basic
  /api/v1/rates?to={to}&from={from}:
    get:
      summary: "List of rates between dates"
      parameters:
        - name: "to"
          in: "path"
          description: "date in yyyy-mm-ddThh:mm:ss format"
          required: true
          type: "DateTime"
        - name: "from"
          in: "path"
          description: "date in yyyy-mm-ddThh:mm:ss format"
          required: true
          type: "DateTime"
      responses:
        200:
          description: "RatesResponse"
          schema:
            $ref: "#/definitions/RatesResponse"
        500:
          description: "Something went wrong"
      tags:
        - rates
definitions:
  RatesResponse:
    type: "array"
    items:
      $ref: "#/definitions/RatesList"
  RatesList:
    type: "object"
    properties:
      Id:
        type: "ObjectID"
      Rates:
        type: "array"
        items:
          $ref: "#/definitions/Rate"
      TimeStamp:
        type: "DateTime"
  Rate:
    type: "object"
    properties:
      Symbol:
        type: "string"
      High:
        type: "float"
      HighChange:
        type: "float"
      Low:
        type: "float"
      LowChange:
        type: "float"
      Volume:
        type: "float"
      VolumeChange:
        type: "float"